### ISSUE TITLE
Historical Forex Ticks At Specific Time

### ISSUE THREAD

**Issue by ijz1361** [Polygon-io/client-examples#1]
Hi,
we need to have the time at a specific time like  11:23:05 2017.08.07 
what is your solution for this case?

**Comment by rjz1371** [comment]
i have this problem too !

**Comment by qrpike** [comment]
We plan to add the ability to request dates with unix timestamps ( ms precision ) for more accurate historic requests.

**Comment by qrpike** [comment]
You can now use unix timestamps as the offset

**Comment by dqii** [comment]
How do you use unix timestamps?
