### ISSUE TITLE
Java Client Library

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/client-examples#10]
Help us create a library for Java users to reference when getting started with Polygon.io.
https://polygon.io/sockets
https://polygon.io/docs/#getting-started

**Comment by justinpolygon** [comment]
Hey @jrbell19, are you okay if I close this issue since we have the official https://github.com/polygon-io/client-jvm now?

**Comment by jrbell19** [comment]
Yep, I think thats fine

Jack Bell
Head of Business Development 
***@***.***​

https://polygon.io​​

www.linkedin.com/in/jack-polygonio

--- original message ---
On February 1, 2023 at 2:16 AM EST ***@***.*** wrote:



Hey @jrbell19, are you okay if I close this issue since we have the official https://github.com/polygon-io/client-jvm now?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---
