### ISSUE TITLE
Unable to subscribe to (Q)uotes channel in websocket client

### ISSUE THREAD

**Issue by wilmorrtr** [polygon-io/client-examples#12]
I am able to successfully subscribe to the Trades channel, but when I attempt to subscribe to the quotes channel, I get an error.

My request:
`{"action":"subscribe","params”:”Q.AAP”}`

Error returned:
`[{"ev":"status","status":"error","message":"Invalid JSON"}]`

I understand my subscription call may be incorrect, but I've been unable to find any reference (other than a table showing channels T, Q, A and AM.  I'd appreciate any assistance you can give!

**Comment by justinpolygon** [comment]
Apologies for the extremely late reply @wilmorrtr. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.
