### ISSUE TITLE
WebSocket C# Connection Error

### ISSUE THREAD

**Issue by zkb-1989** [polygon-io/client-examples#14]
i am trying your polygon websocket code in console C# from github. but it always returns an error, can you please see
![image](https://user-images.githubusercontent.com/60728038/77932762-6c583580-72c7-11ea-811e-6e0d17cedf6d.png)

**Comment by justinpolygon** [comment]
Apologies for the late reply @zkb-1989. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.
