### ISSUE TITLE
auto-reconnect python code

### ISSUE THREAD

**Issue by ravichiripurapu** [polygon-io/client-examples#15]
I'm looking for an auto-reconnect python code for polygon stocks. 

Can you please share me the git repo location. 

I really appreciate your help

**Comment by justinpolygon** [comment]
Apologies for the late reply @ravichiripurapu. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.

We have an official python client here: https://github.com/polygon-io/client-python
