### ISSUE TITLE
Equities?

### ISSUE THREAD

**Issue by kanendosei** [polygon-io/client-examples#2]
I am trying to get this to work with Stocks/equities by using either Q.TICKER or AM.TICKER and have been unsuccessful in my attempts, using the Python example.

params of "C.AUD/USD,C.USD/EUR,C.USD/JPY" return results
params of "AM.AAPL,Q.AAPL,C.USD/EUR,C.EUR/USD" only return Forex/Currency
params of "AM.AAPL,Q.AAPL" connects and joins, but returns no quotes.

**Comment by qrpike** [comment]
Sorry for the delay, we didn't see this.

Are you using websockets? Do you have an active/valid subscription?

Thanks,

**Comment by justinpolygon** [comment]
Is this still an issue @kanendosei? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.
