### ISSUE TITLE
how to use this Poloygon Api in C#

### ISSUE THREAD

**Issue by imshoaibIsmail** [polygon-io/client-examples#21]
i have a situation where i want to provide data to frontend after getting it from polygon.
so i will be making simple Restcall to the point?
and i cann't find the subscribe endpoint in Api Docs.
how can i call this subscribe endpoint to get updates for a particular symbol??

**Comment by justinpolygon** [comment]
Sorry, we currently do not support C#. We do have client libraries for Go, Python, Java, and JS. You could roll your own by hitting the endpoint directly too. The best way to stream events is via our websocket support https://polygon.io/docs/stocks/ws_getting-started.
