### ISSUE TITLE
authenticated but not getting anything

### ISSUE THREAD

**Issue by atifzia** [polygon-io/client-examples#5]

**Comment by atifzia** [comment]
I am trying to run code with valid api key but I am not receiving any data from websoket, 

output : 

`Message: [map[ev:status status:connected message:Connected Successfully]]
Message: [map[message:authenticated ev:status status:success] map[ev:status status:success message:subscribed to: C.AUD/USD]]
`

**Comment by justinpolygon** [comment]
Apologies for the extremely late reply @atifzia. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.
