### ISSUE TITLE
Wolfram Language client?

### ISSUE THREAD

**Issue by arnoudbuzing** [polygon-io/client-examples#6]
If I wanted to write a Wolfram Language (https://www.wolfram.com/language/) client for your API, what would be the best way to go about it?

**Comment by justinpolygon** [comment]
Apologies for the extremely late reply @arnoudbuzing. Is this something that is still on your radar? We suspect not given the time elapsed, but would like to assist if there's still a problem. To be honest, I'm not familiar with building a Wolfram client that accesses an external API. But, after doing some reading it looks like it involves the following steps:

- Familiarize yourself with the Wolfram language and API documentation. Suspect you have this nailed down given you work there :)
- Determine what data or functionality you want to access from the Polygon.io API (via [HTTPClient](https://reference.wolfram.com/language/ref/HTTPRequest.html)).
- Write a script or program in the Wolfram language that makes API requests to the external API and processes the data received.
- Use the Wolfram API functions to format the data and display it in a way that is useful to users. Not sure if this would be use-case dependent or not.
- Test your client thoroughly and make any necessary adjustments.

Pseudo code in Wolfram language probably looks something like:

```
(* Import necessary libraries *)
Needs["HTTPClient`"];

(* Define the API endpoint and any necessary parameters *)
endpoint = "https://api.polygon.io/...";
params = {};

(* Make the API request *)
response = HTTPRequest[endpoint, "Parameters" -> params];

(* Process the response data as necessary *)
data = ImportString[response["Body"], "JSON"];

(* Format and display the data *)
Grid[data, Dividers -> All]
```

I guess it depends on how you prompt folks to access their API key. Probably the best way to get started is to [sign up for a free API key](https://polygon.io/pricing) and kick the tires a bit. Also, there are [extensive API documents](https://polygon.io/docs/stocks/getting-started) on the polygon side that should make fetching data pretty easy. I'll leave this open for a bit if you need help, so please just reply, if not again apologies for the delay.
