### ISSUE TITLE
Python Client Library

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/client-examples#7]
Help us create a library for Python users to reference when getting started with Polygon.io. 
https://polygon.io/sockets
https://polygon.io/docs/#getting-started

**Comment by wjg59701** [comment]
jrbell19: I am a grad student in Data Science starting to do some projects with polygon.io can I message you privately to discuss what kind of content you are looking for here?

**Comment by jrbell19** [comment]
Yes, absolutely! We just need all of our endpoints mapped out in as many languages as possible, to help users integrate and reference when using the feeds.

—
Jack Bell
https://polygon.io

--- original message ---
On November 13, 2019, 9:23 AM EST notifications@github.com wrote:


jrbell19: I am a grad student in Data Science starting to do some projects with polygon.io can I message you privately to discuss what kind of content you are looking for here?

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by herebebeasties** [comment]
This issue should probably be closed now that https://github.com/polygon-io/client-python exists.
