### ISSUE TITLE
NodeJS Client Library

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/client-examples#8]
Help us create a library for NodeJS users to reference when getting started with Polygon.io.
https://polygon.io/sockets
https://polygon.io/docs/#getting-started

**Comment by ao10** [comment]
Hi, I'd like to take a crack at this. 

Is there a private e-mail/Slack/Discord/etc. I can reach out to for more details?

**Comment by jrbell19** [comment]
We have since made a NodeJS library available at https://github.com/polygon-io/client-js

Would you be interested in writing one for C++?

**Comment by justinpolygon** [comment]
Hey @jrbell19, are you okay if I close this issue since we have the official https://github.com/polygon-io/client-js now?

**Comment by jrbell19** [comment]
Sounds good to me!

Jack Bell
Head of Business Development 
***@***.***​

https://polygon.io​​

www.linkedin.com/in/jack-polygonio

--- original message ---
On February 1, 2023 at 2:15 AM EST ***@***.*** wrote:



Hey @jrbell19, are you okay if I close this issue since we have the official https://github.com/polygon-io/client-js now?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---
